In [9]:
import numpy as np
arr=np.array([1,6,2,7,6,5,4])
x=np.where(arr==7)
print(x)

(array([3]),)


In [10]:
x=np.where(arr%2==0)
print(x)

(array([1, 2, 4, 6]),)


In [11]:
x=np.where(arr%3==1)
print(x)

(array([0, 3, 6]),)


In [13]:
import numpy as np
arr=np.array([0,1,2,2,7,8,9])
x=np.searchsorted(arr,8,side='right')
print(x)

6


In [14]:
#sorting of array 1D
import numpy as np
arr=np.array([9,5,2,7,6,4])
print(np.sort(arr))

[2 4 5 6 7 9]


In [16]:
#sorting an 2D array
import numpy as np
arr1=np.array([[7,4,9],[9,1,4]])
print(np.sort(arr1))

[[4 7 9]
 [1 4 9]]


In [23]:
#boolean indexing
import numpy as np
arr2=np.array([31,78,69,100])
x=[True,True,False,True]
newarr=arr2[x]
print(newarr)

[ 31  78 100]


In [29]:
import numpy as np
arr=np.array([31,78,69,100])
filter_arr=arr>70
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True]
[ 78 100]
