In [3]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice=arr[2:6]
print(slice)

[3 4 5 6]


In [4]:
slice2=arr[::2]
print(slice2)

[1 3 5 7 9]


In [5]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
rev_arr=arr[::-1]
print(rev_arr)

[9 8 7 6 5 4 3 2 1]


In [6]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarr=arr[0:2,1:3]
print(subarr)

[[2 3]
 [5 6]]


In [8]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[:2,:1])

[[1]
 [4]]


In [12]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
col1=arr[:,0]
print(col1)

[1 4 7]


In [14]:
import numpy as np
row1=arr[0,:]
print(row1)

[1 2 3]


In [18]:
import numpy as np
arr=array.array('i',[10,20,30,40,50,60])
print(arr[0])
print(arr[3])

TypeError: Field elements must be 2- or 3-tuples, got '10'

In [2]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [3]:
result=np.vstack((arr1,arr2))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [4]:
result=np.dstack((arr1,arr2))
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [12]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([10,20,30,40,50])
result1=np.split(arr1,3)
result2=np.array_split(arr2,3)
print(result1)
print(result2)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([10, 20]), array([30, 40]), array([50])]
