In [8]:
import numpy as np
a=np.array([10,20,30,40])
print("One dimensional array:",a)

One dimensional array: [10 20 30 40]


In [2]:
import numpy as np
b=np.array([[10,20,30,40],[50,60,70,80]])
print("\n Two dimensional array:\n",b)


 Two dimensional array:
 [[10 20 30 40]
 [50 60 70 80]]


In [3]:
import numpy as np
c=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("\n Three dimensional array:\n",c)


 Three dimensional array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
import numpy as np
d=np.zeros((3,5))
print("\n Array with Zeros:\n",d)


 Array with Zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
import numpy as np
e=np.random.random((3,5))
print("\n Array with the random values:\n",e)


 Array with the random values:
 [[0.24307679 0.35281264 0.91828794 0.66846174 0.67557716]
 [0.25366234 0.92762331 0.8847754  0.59605507 0.27020073]
 [0.04853822 0.6862448  0.58394638 0.9920967  0.70037509]]


In [9]:
import numpy as np
f=np.arange(0,10,1)
print("\n sequence value:\n",f)


 sequence value:
 [0 1 2 3 4 5 6 7 8 9]


In [10]:
import numpy as np
orgarr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newarr=orgarr.reshape(4,3)
print("\n Original Array:\n",orgarr)
print("\n Reshaped Array:\n",newarr)


 Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 Reshaped Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
import numpy as np
orgarr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
flatarr=orgarr.flatten()
print("\n Orginal Array:\n",orgarr)
print("\n Flatten Array:\n",flatarr)


 Orginal Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 Flatten Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [35]:
import numpy as np
h=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
size=len(h)
print("dimension array:",h.ndim)
print("my array data type:",h.dtype)
print("length of array:",size)

dimension array: 3
my array data type: int64
length of array: 2


In [3]:
import numpy as np
a=[1,2,3]
a=np.array(a)
newtype=a.astype('float64')
print(newtype)
print(newtype.dtype)

[1. 2. 3.]
float64


In [7]:
import numpy as np
arr=np.array([[1,2,3,4,5,6,7,8,9]])
slice=arr[2,6]
print('slice')

IndexError: index 2 is out of bounds for axis 0 with size 1